base_image_family = "ubuntu-2204-lts"
base_image_project = "ubuntu-os-cloud"
image_family       = "gcrunner-ubuntu2204-x64"
image_description  = "gcrunner image based on Ubuntu 22.04 LTS x64"
image_os           = "ubuntu22"
toolset_file       = "toolsets/toolset-2404.json"
